# @see https://docs.docker.com/compose/compose-file/build/
version: "3.9"

services:
  redis:
    image: "redis:6-alpine"
    ports:
      - "6379:6379"

  mysql:
    image: "mysql:latest"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "coblocks"
    volumes:
      - ./app/coblocks.sql:/docker-entrypoint-initdb.d/coblocks.sql

  # caddy:
  #   image: caddy:2
  #   ports:
  #     - 3000:80
  #     - 1443:443
  #   environment:
  #     - reverse_proxy_from=my-app:3000
  #     - reverse_proxy_to=my-domain.com
  #   volumes:
  #     - caddy:/data

  # coblocks-access:
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile
  #     args:
  #       - target=access
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - mysql
  #   environment:
  #     DATABASE_URL: mysql://root:123456@mysql:3306/coblocks
  #     NODE_ENV: development
  #     PORT: 3000

  coblocks-core:
    build:
      context: ./
      dockerfile: Dockerfile
      target: core
    ports:
      - "5000:5000"
    networks:
      - coblocks
    depends_on:
      - mysql
    environment:
      DATABASE_URL: mysql://root:123456@mysql:3306/coblocks
      NODE_ENV: development

  coblocks-admin:
    build:
      context: ./
      dockerfile: Dockerfile
      target: admin
    ports:
      - "3000:3000"
    networks:
      - coblocks

  coblocks-dashboard:
    build:
      context: ./
      dockerfile: Dockerfile
      target: dashboard
    ports:
      - "5173:5173"
    volumes:
      - ./caddy/Caddyfile-dashboard:/etc/caddy/Caddyfile
    networks:
      - coblocks

networks:
  coblocks:
    driver: bridge
