# @see https://docs.docker.com/compose/compose-file/build/
version: "3.9"

services:
  redis:
    image: "redis:6-alpine"
    ports:
      - "6379:6379"

  mysql:
    image: "mysql:latest"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "coblocks"
    volumes:
      - ./app/coblocks.sql:/docker-entrypoint-initdb.d/coblocks.sql
