version: "3.9"

services:
  redis:
    image: "redis:6-alpine"
    ports:
      - "6379:6379"

  mysql:
    image: "mysql:latest"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "coblocks"
    volumes:
      - ./coblocks.sql:/docker-entrypoint-initdb.d/coblocks.sql

  # coblocks-core:
  #   build:
  #     context: ./core
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - mysql
  #   environment:
  #     DATABASE_URL: mysql://root:123456@mysql:3306/coblocks
  #     NODE_ENV: development
  #     PORT: 3000
